version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules     
    tty: true
    networks: 
      - mynetwork    
    depends_on: 
      db:
        condition: service_healthy  
  
  db:
    image: mysql:5.7               
    command: --innodb-use-native-aio=0    
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password      
      - MYSQL_ROOT_PASSWORD=password
    networks: 
      - mynetwork      
    ports:
      - "3306:3306"         
    healthcheck:
      test: mysqladmin ping -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 55

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks: 
      - mynetwork      
    depends_on: 
      - db
      - app

networks: 
  mynetwork:
    driver: bridge      
